import { analyzeATSWithAI, improveWithAI, matchJobWithAI } from '../services/analysisService.js';
import CV from '../models/CV.js';
import AIUsage from '../models/AIUsage.js';
import ATSAnalysis from '../models/ATSAnalysis.js';
import JobMatch from '../models/JobMatch.js';
import SystemSettings from '../models/SystemSettings.js';
async function checkAI(req,res){ const config=await SystemSettings.findOne({key:'global'}); if(config && !config.aiEnabled) { res.status(403).json({message:'AI features are currently disabled by the administrator.'}); return null; } if(config){ const used=await AIUsage.countDocuments({user:req.user._id,createdAt:{$gte:new Date(Date.now()-24*60*60*1000)}}); if(used>=config.maxAIRequests) {res.status(429).json({message:`Daily AI request limit reached (${config.maxAIRequests}).`}); return null;} } return true; }
export async function ats(req,res){const allowed=await checkAI(req,res); if(!allowed)return; const started=Date.now(); const {cv={},jobDescription=''}=req.body; const result=await analyzeATSWithAI(cv,jobDescription); if(cv?.id)await CV.findOneAndUpdate({_id:cv.id,user:req.user._id},{atsScore:result.score}); await ATSAnalysis.create({user:req.user._id,cv:cv?.id||null,score:result.score,keywords:result.breakdown?Object.keys(result.breakdown):[],missingKeywords:result.missingKeywords||[],suggestions:result.suggestions||[]}); await AIUsage.create({user:req.user._id,feature:'ats',status:'success',model:result.analysisMode==='ai'?'openai':'local-fallback',responseTime:Date.now()-started}); res.json(result);}
export async function ai(req,res){const allowed=await checkAI(req,res); if(!allowed)return; const started=Date.now();const {target,input=''}=req.body;if(!['summary','experience','project','skills','ats'].includes(target))return res.status(400).json({message:'Invalid AI target'});try{const result=await improveWithAI(target,input);await AIUsage.create({user:req.user._id,feature:target,status:'success',model:process.env.OPENAI_API_KEY?'openai':'local-fallback',responseTime:Date.now()-started});res.json({result});}catch(error){await AIUsage.create({user:req.user._id,feature:target,status:'error',error:error.message,responseTime:Date.now()-started});throw error;}}
export async function jobMatch(req,res){const allowed=await checkAI(req,res); if(!allowed)return; if(!req.body.jobDescription)return res.status(400).json({message:'Job description is required'});const result=await matchJobWithAI(req.body.cv||{},req.body.jobDescription);await JobMatch.create({user:req.user._id,cv:req.body.cv?.id||null,jobDescription:req.body.jobDescription,matchScore:result.matchScore,matchedSkills:result.matchedSkills,missingSkills:result.missingSkills,recommendations:result.recommendations});res.json(result);}
